import conclave.dag as con_dag


class Verify:

    def __init__(self, protocol, policy, pid):

        self.protocol = con_dag.OpDag(protocol())
        self.policy = policy
        self.pid = pid

    def verify(self):
        """
        Verification method. Will need to traverse the DAG generated by
        the protocol and compare it against the policy for the given PID.
        """

        if self.protocol:
            print("\n\n\n***Verified***\n\n\n")
            return True

        else:
            raise Exception("No protocol passed to PolicyEngine.")
